-- MySQL Script generated by MySQL Workbench
-- Seg 23 Out 2017 19:43:28 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdsistemast
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdsistemast` ;

-- -----------------------------------------------------
-- Schema bdsistemast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsistemast` DEFAULT CHARACTER SET utf8 ;
USE `bdsistemast` ;

-- -----------------------------------------------------
-- Table `bdsistemast`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `end_num` VARCHAR(45) NOT NULL,
  `end_rua` VARCHAR(45) NOT NULL,
  `end_cidade` VARCHAR(45) NOT NULL,
  `end_estado` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Administrador` (
  `senha` VARCHAR(32) NOT NULL,
  `cod_adm` INT NOT NULL,
  `salario` DOUBLE NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`cod_adm`),
  INDEX `fk_Administrador_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Administrador_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Funcionario` (
  `senha` VARCHAR(32) NOT NULL,
  `cod_func` INT NOT NULL,
  `salario` DOUBLE NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`cod_func`),
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Categoria` (
  `cod_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `beneficios` VARCHAR(45) NOT NULL,
  `valor_mensalidade` DOUBLE NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`SocioTorcedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`SocioTorcedor` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`SocioTorcedor` (
  `cod_st` INT NOT NULL,
  `Categoria_cod_categoria` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`cod_st`),
  INDEX `fk_SocioTorcedor_Categoria_idx` (`Categoria_cod_categoria` ASC),
  INDEX `fk_SocioTorcedor_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_SocioTorcedor_Categoria`
    FOREIGN KEY (`Categoria_cod_categoria`)
    REFERENCES `bdsistemast`.`Categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SocioTorcedor_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Pagamento` (
  `valor` DOUBLE NOT NULL,
  `detalhesPagamento` VARCHAR(45) NOT NULL,
  `SocioTorcedor_cod_st` INT NOT NULL,
  PRIMARY KEY (`SocioTorcedor_cod_st`),
  INDEX `fk_Pagamento_SocioTorcedor1_idx` (`SocioTorcedor_cod_st` ASC),
  CONSTRAINT `fk_Pagamento_SocioTorcedor1`
    FOREIGN KEY (`SocioTorcedor_cod_st`)
    REFERENCES `bdsistemast`.`SocioTorcedor` (`cod_st`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Contato` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Contato` (
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  INDEX `fk_Contato_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Contato_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Telefone` (
  `telefone` VARCHAR(45) NOT NULL,
  `Contato_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`telefone`),
  INDEX `fk_Telefone_Contato1_idx` (`Contato_Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Telefone_Contato1`
    FOREIGN KEY (`Contato_Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Contato` (`Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistemast`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsistemast`.`Email` ;

CREATE TABLE IF NOT EXISTS `bdsistemast`.`Email` (
  `email` VARCHAR(45) NOT NULL,
  `Contato_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_Email_Contato1_idx` (`Contato_Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Email_Contato1`
    FOREIGN KEY (`Contato_Pessoa_idPessoa`)
    REFERENCES `bdsistemast`.`Contato` (`Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
