/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import sistemast.Administrador;
import sistemast.Funcionario;
import sistemast.SocioTorcedor;

/**
 *
 * @author antonio
 */
public class TelaAdmin extends javax.swing.JFrame {
    private Administrador meuadmin;
    private SocioTorcedor st;
    private Funcionario func;
    
    
    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin(Administrador meuadmin) {//Administrador meuadmin
        this.meuadmin = meuadmin;
        //this.meuadmin = meuadmin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MeusDados = new javax.swing.JMenuItem();
        relatorioFinanceiro = new javax.swing.JMenu();
        jMenuPagamento = new javax.swing.JMenu();
        jMenuPGListar = new javax.swing.JMenuItem();
        JMenuPGCadastro = new javax.swing.JMenuItem();
        jMenuPGAlterar = new javax.swing.JMenuItem();
        jMenuPGDeletar = new javax.swing.JMenuItem();
        jMenuItemRelatorioPagamento = new javax.swing.JMenuItem();
        listarSocio = new javax.swing.JMenu();
        jMenuCategoria = new javax.swing.JMenu();
        jMenuCadastrarCategoria = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        cadastrarSocio = new javax.swing.JMenuItem();
        jMenuItemRemoverST = new javax.swing.JMenuItem();
        jMenuAlterarS = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        cadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuAlterarF = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/background.jpg"))); // NOI18N

        jMenu1.setText("Inicio");

        MeusDados.setText("Meus Dados");
        MeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeusDadosActionPerformed(evt);
            }
        });
        jMenu1.add(MeusDados);

        jMenuBar1.add(jMenu1);

        relatorioFinanceiro.setText("Contabilidade");

        jMenuPagamento.setText("Pagamento");

        jMenuPGListar.setText("Listar Pagamento");
        jMenuPGListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGListarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGListar);

        JMenuPGCadastro.setText("Cadastrar Pagamento");
        JMenuPGCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuPGCadastroActionPerformed(evt);
            }
        });
        jMenuPagamento.add(JMenuPGCadastro);

        jMenuPGAlterar.setText("Alterar Pagamento");
        jMenuPGAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGAlterarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGAlterar);

        jMenuPGDeletar.setText("Remover Pagamento");
        jMenuPGDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGDeletarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGDeletar);

        relatorioFinanceiro.add(jMenuPagamento);

        jMenuItemRelatorioPagamento.setText("Relatório Financeiro");
        jMenuItemRelatorioPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioPagamentoActionPerformed(evt);
            }
        });
        relatorioFinanceiro.add(jMenuItemRelatorioPagamento);

        jMenuBar1.add(relatorioFinanceiro);

        listarSocio.setText("Socio");

        jMenuCategoria.setText("Categoria");

        jMenuCadastrarCategoria.setText("Cadastrar");
        jMenuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenuCategoria.add(jMenuCadastrarCategoria);

        listarSocio.add(jMenuCategoria);

        jMenuItem4.setText("Listar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuItem4);

        cadastrarSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        cadastrarSocio.setText("Cadastrar");
        cadastrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarSocioActionPerformed(evt);
            }
        });
        listarSocio.add(cadastrarSocio);

        jMenuItemRemoverST.setText("Remover");
        jMenuItemRemoverST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverSTActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuItemRemoverST);

        jMenuAlterarS.setText("Alterar Dados");
        jMenuAlterarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarSActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuAlterarS);

        jMenuItem12.setText("Delegar Cargos");
        listarSocio.add(jMenuItem12);

        jMenuBar1.add(listarSocio);

        jMenu4.setText("Funcionario");

        jMenuItem3.setText("Listar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        cadastrarFuncionario.setText("Cadastrar");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(cadastrarFuncionario);

        jMenuAlterarF.setText("Alterar ");
        jMenuAlterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarFActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAlterarF);

        jMenuItem8.setText("Remover");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Opcões");

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaListaFuncionarios t = new TelaListaFuncionarios();
        t.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario(func);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void cadastrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarSocioActionPerformed
        TelaCadastroST tela = new TelaCadastroST(st);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarSocioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_CANCEL_OPTION);//Vai sair realmente?
        
        if(ans == 0){//Se sim...
            this.dispose();
            Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
        }
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed


    private void jMenuItemRemoverSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverSTActionPerformed
       TelaRemoveST t = new TelaRemoveST();
       t.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItemRemoverSTActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaListaDeSTs l = new TelaListaDeSTs();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        TelaRemoveFuncionario l = new TelaRemoveFuncionario();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuAlterarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarSActionPerformed
        // TODO add your handling code here:
        /*TelaAlterarST altst = new TelaAlterarST();
        altst.setVisible(true);*/
        TelaListaDeAlteracaoSTs lta1 = new TelaListaDeAlteracaoSTs();
        lta1.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarSActionPerformed

    private void jMenuAlterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarFActionPerformed
        // TODO add your handling code here:
        TelaListaDeAlteracaoFuncionarios ltf1 = new TelaListaDeAlteracaoFuncionarios();
        ltf1.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarFActionPerformed

    private void jMenuPGDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGDeletarActionPerformed
        // TODO add your handling code here:
        TelaRemovePagamento removePag = new TelaRemovePagamento();
        removePag.setVisible(true);
    }//GEN-LAST:event_jMenuPGDeletarActionPerformed

    private void JMenuPGCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuPGCadastroActionPerformed
        // TODO add your handling code here:
        TelaCadastroPagamento cadastroPag = new TelaCadastroPagamento();
        cadastroPag.setVisible(true);
    }//GEN-LAST:event_JMenuPGCadastroActionPerformed

    private void jMenuPGAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGAlterarActionPerformed
        // TODO add your handling code here:
        TelaListaDeAlteracaoPagamento alteraPag = new TelaListaDeAlteracaoPagamento();
        alteraPag.setVisible(true);
    }//GEN-LAST:event_jMenuPGAlterarActionPerformed

    private void jMenuPGListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGListarActionPerformed
        // TODO add your handling code here:
        TelaListaPagamento listaPag = new TelaListaPagamento();
        listaPag.setVisible(true);
    }//GEN-LAST:event_jMenuPGListarActionPerformed

    private void jMenuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastroCategoria cadastraCat = new TelaCadastroCategoria();
        cadastraCat.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarCategoriaActionPerformed

    private void jMenuItemRelatorioPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioPagamentoActionPerformed
        // TODO add your handling code here:
        TelaRelatorioPagamento relatorio = new TelaRelatorioPagamento();
        relatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioPagamentoActionPerformed

    private void MeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeusDadosActionPerformed
        // TODO add your handling code here:
        TelaVerDadosAdministrador telaAdm1 = new TelaVerDadosAdministrador(this.meuadmin);
        telaAdm1.setVisible(true);
    }//GEN-LAST:event_MeusDadosActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuPGCadastro;
    private javax.swing.JMenuItem MeusDados;
    private javax.swing.JMenuItem cadastrarFuncionario;
    private javax.swing.JMenuItem cadastrarSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAlterarF;
    private javax.swing.JMenuItem jMenuAlterarS;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarCategoria;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemRelatorioPagamento;
    private javax.swing.JMenuItem jMenuItemRemoverST;
    private javax.swing.JMenuItem jMenuPGAlterar;
    private javax.swing.JMenuItem jMenuPGDeletar;
    private javax.swing.JMenuItem jMenuPGListar;
    private javax.swing.JMenu jMenuPagamento;
    private javax.swing.JMenu listarSocio;
    private javax.swing.JMenu relatorioFinanceiro;
    // End of variables declaration//GEN-END:variables
}
