/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import dao.CategoriaDAO;
import dao.PagamentoDAO;
import dao.SocioTorcedorDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistemast.Categoria;
import sistemast.Pagamento;
import sistemast.SocioTorcedor;

/**
 *
 * @author antonio
 */
public class TelaRemoveCategoria extends javax.swing.JFrame {

    //ArrayList<SocioTorcedor> lista;
    /**
     * Creates new form TelaCadastroPagamento
     */
    public TelaRemoveCategoria() {
        initComponents();
        this.setLocationRelativeTo(null);
        preenche();
        
    }
    
    public void preenche(){
        
           // para preencher a lista:
            CategoriaDAO db = new CategoriaDAO();
            Categoria cat = new Categoria();
            ArrayList<Object> listaCat = db.consulta(cat);
            String[] dados = new String[listaCat.size()];
            Categoria categoria;
            for(int i = 0; i < listaCat.size(); i++){
                categoria = (Categoria) listaCat.get(i);
                dados[i] = categoria.getNome();
            }
            this.jListCategoria.setListData(dados);
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRemover = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategoria = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jListCategoria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRemover))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(91, 91, 91)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButtonRemover)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        this.removeCategoria();
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    public void removeCategoria(){//Testar antes para ver se pode mesmo remover o ST
        
        int x = this.jListCategoria.getSelectedIndex();
        
        CategoriaDAO db = new CategoriaDAO();
        Categoria cat = new Categoria();
        ArrayList<Object> listaCat = db.consulta(cat);
        Categoria aRemover = (Categoria) listaCat.get(x);
        
        //Teste pra ver se alguem eh desta categoria
        
        SocioTorcedorDAO stdao = new SocioTorcedorDAO();
        SocioTorcedor st = new SocioTorcedor();
        
        ArrayList<Object> listaST = stdao.consulta(st);
        
        for(int i = 0; i < listaST.size(); i++){
            st = (SocioTorcedor) listaST.get(i);
            if(st.checaCategoria(aRemover)){
                JOptionPane.showMessageDialog(null, "Incapaz de Remover, altere antes as categorias dos sócios participantes.");
                
                this.dispose();
                return;//Pausa execucao pra nao ficar abrindo direto
            }
        
        
        }
        
        JOptionPane.showMessageDialog(null,"Vai dar pra remover sim.");//continua
        
        db.exclui(aRemover);
        
        
    
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCadastroPagamento().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
