/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import sistemast.Funcionario;
import sistemast.SocioTorcedor;

/**
 *
 * @author antonio
 */
public class TelaFuncionario extends javax.swing.JFrame {
    
    private Funcionario meufuncionario;
    private SocioTorcedor st;
    
    
    
    /**
     * Creates new form TelaAdmin
     */
    public TelaFuncionario(Funcionario meufuncionario) {
        this.meufuncionario = meufuncionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MeusDados = new javax.swing.JMenuItem();
        jMenuItemAlterarMeusDados = new javax.swing.JMenuItem();
        relatorioFinanceiro = new javax.swing.JMenu();
        jMenuPagamento = new javax.swing.JMenu();
        jMenuPGListar = new javax.swing.JMenuItem();
        JMenuPGCadastro = new javax.swing.JMenuItem();
        jMenuPGAlterar = new javax.swing.JMenuItem();
        jMenuPGDeletar = new javax.swing.JMenuItem();
        listarSocio = new javax.swing.JMenu();
        jMenuListaS = new javax.swing.JMenuItem();
        cadastrarSocio = new javax.swing.JMenuItem();
        jMenuRemoveS = new javax.swing.JMenuItem();
        jMenuAlterarDados = new javax.swing.JMenuItem();
        jMenuDelegarCargos = new javax.swing.JMenuItem();
        jMenuCategoria = new javax.swing.JMenu();
        jMenuCadastrarCategoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/background.jpg"))); // NOI18N

        jMenu1.setText("Inicio");

        MeusDados.setText("Meus Dados");
        MeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeusDadosActionPerformed(evt);
            }
        });
        jMenu1.add(MeusDados);

        jMenuItemAlterarMeusDados.setText("Alterar Meus Dados");
        jMenuItemAlterarMeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarMeusDadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAlterarMeusDados);

        jMenuBar1.add(jMenu1);

        relatorioFinanceiro.setText("Contabilidade");

        jMenuPagamento.setText("Pagamento");

        jMenuPGListar.setText("Listar Pagamento");
        jMenuPGListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGListarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGListar);

        JMenuPGCadastro.setText("Cadastrar Pagamento");
        JMenuPGCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuPGCadastroActionPerformed(evt);
            }
        });
        jMenuPagamento.add(JMenuPGCadastro);

        jMenuPGAlterar.setText("Alterar Pagamento");
        jMenuPGAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGAlterarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGAlterar);

        jMenuPGDeletar.setText("Remover Pagamento");
        jMenuPGDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPGDeletarActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuPGDeletar);

        relatorioFinanceiro.add(jMenuPagamento);

        jMenuBar1.add(relatorioFinanceiro);

        listarSocio.setText("Socio");

        jMenuListaS.setText("Listar");
        jMenuListaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaSActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuListaS);

        cadastrarSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        cadastrarSocio.setText("Cadastrar");
        cadastrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarSocioActionPerformed(evt);
            }
        });
        listarSocio.add(cadastrarSocio);

        jMenuRemoveS.setText("Remover");
        jMenuRemoveS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRemoveSActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuRemoveS);

        jMenuAlterarDados.setText("Alterar Dados");
        jMenuAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarDadosActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuAlterarDados);

        jMenuDelegarCargos.setText("Delegar Cargos");
        jMenuDelegarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDelegarCargosActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuDelegarCargos);

        jMenuCategoria.setText("Categoria");

        jMenuCadastrarCategoria.setText("Cadastrar");
        jMenuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenuCategoria.add(jMenuCadastrarCategoria);

        listarSocio.add(jMenuCategoria);

        jMenuBar1.add(listarSocio);

        jMenu5.setText("Opcões");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarSocioActionPerformed
        TelaCadastroST tela = new TelaCadastroST(st);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarSocioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        int ans = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_CANCEL_OPTION);//Vai sair realmente?
        
        if(ans == 0){//Se sim...
            Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            this.dispose();
        
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarDadosActionPerformed
        // TODO add your handling code here:
//        TelaAlterarST altst = new TelaAlterarST();
//        altst.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarDadosActionPerformed

    private void jMenuListaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaSActionPerformed
        
        TelaListaDeSTs l = new TelaListaDeSTs();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuListaSActionPerformed

    private void jMenuRemoveSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRemoveSActionPerformed
        TelaRemoveST t = new TelaRemoveST();
       t.setVisible(true);
    }//GEN-LAST:event_jMenuRemoveSActionPerformed

    private void jMenuDelegarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDelegarCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDelegarCargosActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuPGDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGDeletarActionPerformed
        // TODO add your handling code here:
        TelaRemovePagamento removePag = new TelaRemovePagamento();
        removePag.setVisible(true);
    }//GEN-LAST:event_jMenuPGDeletarActionPerformed

    private void JMenuPGCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuPGCadastroActionPerformed
        // TODO add your handling code here:
        TelaCadastroPagamento cadastroPag = new TelaCadastroPagamento();
        cadastroPag.setVisible(true);
    }//GEN-LAST:event_JMenuPGCadastroActionPerformed

    private void jMenuPGAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGAlterarActionPerformed
        // TODO add your handling code here:
        TelaListaDeAlteracaoPagamento alteraPag = new TelaListaDeAlteracaoPagamento();
        alteraPag.setVisible(true);
    }//GEN-LAST:event_jMenuPGAlterarActionPerformed

    private void jMenuPGListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPGListarActionPerformed
        // TODO add your handling code here:
        TelaListaPagamento listaPag = new TelaListaPagamento();
        listaPag.setVisible(true);
    }//GEN-LAST:event_jMenuPGListarActionPerformed

    private void MeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeusDadosActionPerformed
        // TODO add your handling code here:
        TelaVerDadosFuncionario telaD1 = new TelaVerDadosFuncionario(this.meufuncionario);
        telaD1.setVisible(true);
    }//GEN-LAST:event_MeusDadosActionPerformed

    private void jMenuItemAlterarMeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarMeusDadosActionPerformed
        // TODO add your handling code here:
        TelaAlterarFuncionario telaA1 = new TelaAlterarFuncionario(this.meufuncionario);
        telaA1.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarMeusDadosActionPerformed

    private void jMenuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastroCategoria cadastraCat = new TelaCadastroCategoria();
        cadastraCat.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarCategoriaActionPerformed
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuPGCadastro;
    private javax.swing.JMenuItem MeusDados;
    private javax.swing.JMenuItem cadastrarSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAlterarDados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarCategoria;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenuItem jMenuDelegarCargos;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAlterarMeusDados;
    private javax.swing.JMenuItem jMenuListaS;
    private javax.swing.JMenuItem jMenuPGAlterar;
    private javax.swing.JMenuItem jMenuPGDeletar;
    private javax.swing.JMenuItem jMenuPGListar;
    private javax.swing.JMenu jMenuPagamento;
    private javax.swing.JMenuItem jMenuRemoveS;
    private javax.swing.JMenu listarSocio;
    private javax.swing.JMenu relatorioFinanceiro;
    // End of variables declaration//GEN-END:variables
}
