/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import sistemast.SocioTorcedor;

/**
 *
 * @author antonio
 */
public class TelaFuncionario extends javax.swing.JFrame {
    SocioTorcedor st;
    
    
    /**
     * Creates new form TelaAdmin
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MeusDados = new javax.swing.JMenuItem();
        relatorioFinanceiro = new javax.swing.JMenu();
        listarSocio = new javax.swing.JMenu();
        jMenuListaS = new javax.swing.JMenuItem();
        cadastrarSocio = new javax.swing.JMenuItem();
        jMenuRemoveS = new javax.swing.JMenuItem();
        jMenuAlterarDados = new javax.swing.JMenuItem();
        jMenuDelegarCargos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/background.jpg"))); // NOI18N

        jMenu1.setText("Inicio");

        MeusDados.setText("Meus Dados");
        jMenu1.add(MeusDados);

        jMenuBar1.add(jMenu1);

        relatorioFinanceiro.setText("Contabilidade");
        jMenuBar1.add(relatorioFinanceiro);

        listarSocio.setText("Socio");

        jMenuListaS.setText("Listar");
        jMenuListaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaSActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuListaS);

        cadastrarSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        cadastrarSocio.setText("Cadastrar");
        cadastrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarSocioActionPerformed(evt);
            }
        });
        listarSocio.add(cadastrarSocio);

        jMenuRemoveS.setText("Remover");
        jMenuRemoveS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRemoveSActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuRemoveS);

        jMenuAlterarDados.setText("Alterar Dados");
        jMenuAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarDadosActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuAlterarDados);

        jMenuDelegarCargos.setText("Delegar Cargos");
        jMenuDelegarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDelegarCargosActionPerformed(evt);
            }
        });
        listarSocio.add(jMenuDelegarCargos);

        jMenuBar1.add(listarSocio);

        jMenu5.setText("Opcões");

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarSocioActionPerformed
        TelaCadastroST tela = new TelaCadastroST(st);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarSocioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        int ans = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_CANCEL_OPTION);//Vai sair realmente?
        
        if(ans == 0){//Se sim...
            this.dispose();
        
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarDadosActionPerformed
        // TODO add your handling code here:
//        TelaAlterarST altst = new TelaAlterarST();
//        altst.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarDadosActionPerformed

    private void jMenuListaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaSActionPerformed
        
        TelaListaDeSTs l = new TelaListaDeSTs();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuListaSActionPerformed

    private void jMenuRemoveSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRemoveSActionPerformed
        TelaRemoveST t = new TelaRemoveST();
       t.setVisible(true);
    }//GEN-LAST:event_jMenuRemoveSActionPerformed

    private void jMenuDelegarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDelegarCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDelegarCargosActionPerformed
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MeusDados;
    private javax.swing.JMenuItem cadastrarSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAlterarDados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDelegarCargos;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuListaS;
    private javax.swing.JMenuItem jMenuRemoveS;
    private javax.swing.JMenu listarSocio;
    private javax.swing.JMenu relatorioFinanceiro;
    // End of variables declaration//GEN-END:variables
}
